// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjbdIZgVx39GC4dKUp0HuL3vgEYlIN3Fg',
    appId: '1:56232375916:web:74d8725d6d1a9641e4ca49',
    messagingSenderId: '56232375916',
    projectId: 'senior-care-management',
    authDomain: 'senior-care-management.firebaseapp.com',
    storageBucket: 'senior-care-management.firebasestorage.app',
    measurementId: 'G-TWRNGWK0RY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKFpfWkd4aKLLHRpbbpMImFf1U0PcDqps',
    appId: '1:56232375916:android:8814f588237e19b3e4ca49',
    messagingSenderId: '56232375916',
    projectId: 'senior-care-management',
    storageBucket: 'senior-care-management.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqvSXlano78PdBe_9Up4keuMLPEiIw470',
    appId: '1:56232375916:ios:12c1120e55570b7fe4ca49',
    messagingSenderId: '56232375916',
    projectId: 'senior-care-management',
    storageBucket: 'senior-care-management.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqvSXlano78PdBe_9Up4keuMLPEiIw470',
    appId: '1:56232375916:ios:12c1120e55570b7fe4ca49',
    messagingSenderId: '56232375916',
    projectId: 'senior-care-management',
    storageBucket: 'senior-care-management.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjbdIZgVx39GC4dKUp0HuL3vgEYlIN3Fg',
    appId: '1:56232375916:web:8c7dc7f012fc9f6fe4ca49',
    messagingSenderId: '56232375916',
    projectId: 'senior-care-management',
    authDomain: 'senior-care-management.firebaseapp.com',
    storageBucket: 'senior-care-management.firebasestorage.app',
    measurementId: 'G-90HJTCXNPJ',
  );
}
